### ISSUE TITLE
Unable to copy to specific folders

### ISSUE THREAD

**Issue by iFieldSmart-Tech** [rohitcoder/BBB-AWS-S3#4]
I am trying to move recordings to a specific folder in my s3 bucket. I have entered the following line in the file writing.js,
const url = "https://my-bucket-name.amazonaws.com/My-Folder-Name/"+meetingId;;
But it still copies the folder into the root folder, in the bucket and not in the subdirectory "My-Folder-Name". Am i doing anything wrong or is this a limitation within the code?

**Comment by rohitcoder** [comment]
@iFieldSmart-Tech ,

You need to change a line of code in bbb-s3.py

Can you please try this, and let me know if this works.

openn bbb-s3.py at change line 60

**From**
```python
uploaded = upload_to_aws(elem, BUCKET_NAME, relative_path)
```

**To**
```python
uploaded = upload_to_aws(elem, BUCKET_NAME, "My-Folder-Name"+"/"+relative_path)
```

**Comment by iFieldSmart-Tech** [comment]
That got it working! Thanks a lot Rohit!
