### ISSUE TITLE
BBB v2.3

### ISSUE THREAD

**Issue by pbdco** [rohitcoder/BBB-AWS-S3#5]
Hi there @rohitcoder ! It seems the new BBB 2.3 version is not using the /playback/presentation/**2.0**/playback.html?meetingId={meetingId} anymore...... will this still work? 🤔

The new path is: /playback/presentation/2.3/{meetingID}

**Comment by rohitcoder** [comment]
> Hi there @rohitcoder ! It seems the new BBB 2.3 version is not using the /playback/presentation/**2.0**/playback.html?meetingId={meetingId} ...... will this still work? 🤔
> 
> 
> 
> The new path is: /playback/presentation/2.3/{meetingID}

Yes it should work as long as something else not changed, please check it and let us know, so that i can update main source code

**Comment by pbdco** [comment]
> > Hi there @rohitcoder ! It seems the new BBB 2.3 version is not using the /playback/presentation/**2.0**/playback.html?meetingId={meetingId} ...... will this still work? 🤔
> > The new path is: /playback/presentation/2.3/{meetingID}
> 
> Yes it should work as long as something else not changed, please check it and let us know, so that i can update main source code

Thanks for your quick reply @rohitcoder , I edited my earlier comment to let you know the new path structure:

 /playback/presentation/2.3/{meetingID}

**Comment by pbdco** [comment]
BTW @rohitcoder now I am trying with the BBB v2.2 and I cannot visualize the recordings from the S3 as well. 
The files are being uploaded to the bucket, but when I try to access to one recording using the same path structure as my actual server, I get "Access Denied" (note: the bucket is 100% public and I can open specific files like the slides .png's correctly), but it seems that it doesn't show the presentation if I use the link.

Example:
My actual bbbserver presentation link = https://bbbserver.mydomain.com/playback/presentation/2.0/playback.html?meetingId=15ab682d1f2f3084f3f739a32c5f552268416dbf-1620013044142 

The S3 link = https://bbb-bucket.s3.amazonaws.com/15ab682d1f2f3084f3f739a32c5f552268416dbf-1620013044142/playback/presentation/2.0/playback.html?meetingId=15ab682d1f2f3084f3f739a32c5f552268416dbf-1620013044142

Im using https://bbb-bucket.s3.amazonaws.com/**{meetingId}**/playback/presentation/2.0/playback.html?meetingId=**{meetingId}** because this is how the recordings are uploaded:

![image](https://user-images.githubusercontent.com/64397076/116839755-dd90a900-aba9-11eb-9f5a-4a95a8587b8c.png)

Thank you for your help.

PS:

My Bucket policy and CORS are set accordingly:

Policy:
`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::my-bbb-bucket/*"
        }
    ]
}
`


CORS:
`[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "HEAD",
            "GET",
            "PUT",
            "POST",
            "DELETE"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [
            "ETag",
            "x-amz-meta-custom-header"
        ]
    }
]`

**Comment by pbdco** [comment]
Hi there @rohitcoder , any clue with this?

**Comment by rohitcoder** [comment]
Can you please share link of any recorded meeting which isn't working for you? You can delete your comment after we solve this, i am not having BBB setup right now

**Comment by hamza3055** [comment]
> > > Hi there @rohitcoder ! It seems the new BBB 2.3 version is not using the /playback/presentation/**2.0**/playback.html?meetingId={meetingId} ...... will this still work? 🤔
> > > The new path is: /playback/presentation/2.3/{meetingID}
> > 
> > 
> > Yes it should work as long as something else not changed, please check it and let us know, so that i can update main source code
> 
> Thanks for your quick reply @rohitcoder , I edited my earlier comment to let you know the new path structure:
> 
> /playback/presentation/2.3/{meetingID}

please guide me where to use this path as if you are referring to the step where we make changes in writing.js  then there is no /lib directory in 2.3 directory

**Comment by rohitcoder** [comment]
Closing this because of no response....
